### ISSUE TITLE
No access to completeness/post-trial report

### ISSUE THREAD

**Issue by ij-cope** [ouh-churchill/COPE#342]
@marshalc 

thanks for the work on #336 

Unfortunately my access right do not allow me to open a case and add the data.

I do have access to Admin and could add 'sys-admin' to my rights to finish this bit and then revoke them again?

Thank you to advise

**Comment by ij-cope** [comment]
@marshalc 

I also noticed I do not have access to any of the Forms except the Adverse Event forms - I would, as central investigator, needs (at least) reading rights to all of the data in the system.

**Comment by ij-cope** [comment]
@marshalc 

I seem to have, inadvertently, closed this issue.
It is, however, still an issue.

Thanks to have a look.

**Comment by marshalc** [comment]
Noted, thank you @ij-cope. I'll investigate this week.

**Comment by marshalc** [comment]
Try now @ij-cope 

The quick fix is that I've added you to the Centra Co-ordinator's role. The longer answer is that as protocol defined the X Investigator's roles as being blinded to certain information, that role has not got permissions for a range of things. Since the trial is closed and you're acting as the defacto Co-ordinator now, the quick fix makes more sense than trying to introduce a new layer of permissions based on if the trial is still open/recruiting vs closed.

**Comment by ij-cope** [comment]
thanks @marshalc 

Access works, I'll populate these forms over the next days to weeks.
